keys:
  - &kloenk_age age1p06k9fwwdhwcx6qxt5fyypkdk9wpkhk5fhyzjnykaymz32nwsakqwyfjqm
  - &mortik_age age16kshm3f9cwlhc5eq3fkg6j6cwnfraj5psl5s564nr43mvg0cvdps95s045
creation_rules:
  - path_regex: secrets/social[^/]*\.yaml$
    key_groups:
    - age:
      - *kloenk_age
      - *mortik_age
      - age1f2h5dc7nyvcp0l49t2d8jhm60nh4gts5pff5h0rkxkvx55z6e3ls69exw8
      #- *server_social
